swagger: '2.0'
info:
  title: Flask API Documentation
  description: Documentation for the Flask API endpoints
  version: '1.0'
paths:
  /animals:
    get:
      summary: Get Animals list
      responses:
        '200':
          description: Getting list of animals
    post:
      summary: Create a new Animal
      parameters:
        - in: body
          name: body
          description: Animal object
          required: true
          schema:
            $ref: '#/definitions/Animal'
      responses:
        '201':
          description: New animal created successfully
  /animals/{animal_id}:
    get:
      summary: Get Animal list specifically
      parameters:
        - in: path
          name: animal_id
          description: ID of the animal to retrieve
          required: true
          type: integer
          format: int64
      responses:
        '201':
          description: Getting list of animal specifically
    put:
      summary: Update an Animal
      parameters:
        - in: path
          name: animal_id
          description: ID of the animal to update
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Animal object
          required: true
          schema:
            $ref: '#/definitions/Animal'
      responses:
        '200':
          description: Animal updated successfully
        '404':
          description: Animal not found
    delete:
      summary: Delete an Animal
      parameters:
        - in: path
          name: animal_id
          description: ID of the animal to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Animal deleted successfully
        '404':
          description: Animal not found
  /employees:
    get:
      summary: Get Employees list
      responses:
        '200':
          description: Getting list of employees
    post:
      summary: Create a new Employee
      parameters:
        - in: body
          name: body
          description: Employee object
          required: true
          schema:
            $ref: '#/definitions/Employee'
      responses:
        '201':
          description: New employee created successfully
  /employees/{employee_id}:
    get:
      summary: Get Employee details
      parameters:
        - in: path
          name: employee_id
          description: ID of the employee to retrieve
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Employee details retrieved successfully
        '404':
          description: Employee not found
    put:
      summary: Update an Employee
      parameters:
        - in: path
          name: employee_id
          description: ID of the employee to update
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Employee object
          required: true
          schema:
            $ref: '#/definitions/Employee'
      responses:
        '200':
          description: Employee updated successfully
        '404':
          description: Employee not found
    delete:
      summary: Delete an Employee
      parameters:
        - in: path
          name: employee_id
          description: ID of the employee to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Employee deleted successfully
        '404':
          description: Employee not found
definitions:
  Animal:
    type: object
    required:
      - species
      - age
      - gender
      - special_requirements
    properties:
      species:
        type: string
        description: The species of the animal
      age:
        type: integer
        description: The age of the animal
      gender:
        type: string
        description: The gender of the animal
      special_requirements:
        type: string
        description: Special requirements for the animal
  Employee:
    type: object
    required:
      - name
      - email
      - phone
      - role
      - schedule
    properties:
      name:
        type: string
        description: The name of the employee
      email:
        type: string
        format: email
        description: The email address of the employee
      phone:
        type: string
        description: The phone number of the employee
      role:
        type: string
        description: The role of the employee
      schedule:
        type: string
        description: The schedule of the employee