from flask import Blueprint, jsonify
from flasgger import swag_from

reports_bp = Blueprint('reports', __name__)

animals_report = {
    "species_distribution": {
        "Lion": 5,
        "Elephant": 3,
        "Tiger": 2
    },
    "gender_distribution": {
        "Male": 5,
        "Female": 5
    },
    "enclosure_distribution": {
        "Savannah": 3,
        "Jungle": 2,
        "Mountain": 5
    }
}

visitors_report = {
    "ticket_type": {
        "Adult": 150,
        "Child": 50,
        "Senior": 30
    },
    "date": {
        "2023-06-01": 20,
        "2023-06-02": 30,
        "2023-06-03": 40
    },
    "feedback": {
        "Excellent": 50,
        "Good": 100,
        "Average": 20
    }
}

revenue_report = {
    "ticket_type": {
        "Adult": 3000,
        "Child": 1000,
        "Senior": 600
    },
    "event_type": {
        "Concert": 5000,
        "Workshop": 2000
    },
    "date": {
        "2023-06-01": 500,
        "2023-06-02": 1000,
        "2023-06-03": 1500
    }
}

@reports_bp.route('/reports/animals', methods=['GET'])
@swag_from({
    'responses': {
        200: {
            'description': 'Retrieve a report on the number and distribution of animals in the zoo, grouped by species, gender and enclosures.',
            'schema': {
                'type': 'object',
                'properties': {
                    'species_distribution': {
                        'type': 'object',
                        'additionalProperties': {'type': 'integer'}
                    },
                    'gender_distribution': {
                        'type': 'object',
                        'additionalProperties': {'type': 'integer'}
                    },
                    'enclosure_distribution': {
                        'type': 'object',
                        'additionalProperties': {'type': 'integer'}
                    }
                }
            }
        }
    }
})
def get_animals_report():
    return jsonify(animals_report), 200

@reports_bp.route('/reports/visitors', methods=['GET'])
@swag_from({
    'responses': {
        200: {
            'description': 'Retrieve a report on the number and behavior of visitors in the zoo, grouped by ticket type, date and feedback.',
            'schema': {
                'type': 'object',
                'properties': {
                    'ticket_type': {
                        'type': 'object',
                        'additionalProperties': {'type': 'integer'}
                    },
                    'date': {
                        'type': 'object',
                        'additionalProperties': {'type': 'integer'}
                    },
                    'feedback': {
                        'type': 'object',
                        'additionalProperties': {'type': 'integer'}
                    }
                }
            }
        }
    }
})
def get_visitors_report():
    return jsonify(visitors_report), 200

@reports_bp.route('/reports/revenue', methods=['GET'])
@swag_from({
    'responses': {
        200: {
            'description': 'Retrieve a report on the revenue generated by the zoo, grouped by ticket type, event type and date.',
            'schema': {
                'type': 'object',
                'properties': {
                    'ticket_type': {
                        'type': 'object',
                        'additionalProperties': {'type': 'integer'}
                    },
                    'event_type': {
                        'type': 'object',
                        'additionalProperties': {'type': 'integer'}
                    },
                    'date': {
                        'type': 'object',
                        'additionalProperties': {'type': 'integer'}
                    }
                }
            }
        }
    }
})
def get_revenue_report():
    return jsonify(revenue_report), 200
